In [20]:
import pandas as pd
import re
import torch # If using a GPU
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

In [21]:
dbert_tokenizer = AutoTokenizer.from_pretrained("dslim/distilbert-NER")
dbert_model = AutoModelForTokenClassification.from_pretrained("dslim/distilbert-NER")
dbert_nlp = pipeline("ner", model=dbert_model, tokenizer=dbert_tokenizer, aggregation_strategy="max")

ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/dslim/distilbert-NER/tree/main/additional_chat_templates?recursive=False&expand=False (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016D37D13680>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 2a524a18-0f01-4491-b83e-64e831804521)')

In [ ]:
uncased_tokenizer = AutoTokenizer.from_pretrained("issifuamajeed/distilbert-base-uncased-finetuned-ner")
uncased_model = AutoModelForTokenClassification.from_pretrained("issifuamajeed/distilbert-base-uncased-finetuned-ner")
uncased_nlp = pipeline("ner", model=uncased_model, tokenizer=uncased_tokenizer, aggregation_strategy="max")

In [4]:
# Get Kaggle dataset
reviews_df = pd.read_csv('datasets/food_reviews_with_product_names.csv')
reviews_df = reviews_df.set_index('Id')
reviews_df

,ProductId,Score,Summary,Text,ItemName
Id,,,,,
5,B006K2ZZ7K,5,Great taffy,Great taffy at a great price. There was a wid...,"Salt Water Taffy - Assorted, 5 lbs"
6,B006K2ZZ7K,4,Nice Taffy,I got a wild hair for taffy and ordered this f...,"Salt Water Taffy - Assorted, 5 lbs"
7,B006K2ZZ7K,5,Great! Just as good as the expensive brands!,This saltwater taffy had great flavors and was...,"Salt Water Taffy - Assorted, 5 lbs"
8,B006K2ZZ7K,5,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,"Salt Water Taffy - Assorted, 5 lbs"
14,B001GVISJM,4,fresh and greasy!,good flavor! these came securely packed... the...,"TWIZZLERS Twists, Strawberry Flavored Licorice..."
...,...,...,...,...,...
568447,B001EO7N10,2,Mixed wrong,I had ordered some of these a few months back ...,"Taste Specialty Foods, Five Spice Powder, 16-O..."
568448,B001EO7N10,5,"If its all natural, this is like panacea of Sp...","Hoping there is no MSG in this, this tastes ex...","Taste Specialty Foods, Five Spice Powder, 16-O..."
568449,B001EO7N10,5,Very large ground spice jars.,My only complaint is that there's so much of i...,"Taste Specialty Foods, Five Spice Powder, 16-O..."
568450,B001EO7N10,5,Will not do without,Great for sesame chicken..this is a good if no...,"Taste Specialty Foods, Five Spice Powder, 16-O..."
568454,B001LR2CU2,5,Great Honey,"I am very satisfied ,product is as advertised,...",Stakich Ginkgo BILOBA Enriched RAW Honey 5-lb ...

In [5]:
reviews_4star_df = reviews_df[reviews_df['Score'] == 4]
reviews_4star_df

,ProductId,Score,Summary,Text,ItemName
Id,,,,,
6,B006K2ZZ7K,4,Nice Taffy,I got a wild hair for taffy and ordered this f...,"Salt Water Taffy - Assorted, 5 lbs"
14,B001GVISJM,4,fresh and greasy!,good flavor! these came securely packed... the...,"TWIZZLERS Twists, Strawberry Flavored Licorice..."
28,B001GVISJM,4,Great Bargain for the Price,I was so glad Amazon carried these batteries. ...,"TWIZZLERS Twists, Strawberry Flavored Licorice..."
33,B001EO5QW8,4,Best of the Instant Oatmeals,McCann's Instant Oatmeal is great if you must ...,"McCANN'S Instant Irish Oatmeal, Variety Pack o..."
34,B001EO5QW8,4,Good Instant,This is a good instant oatmeal from the best o...,"McCANN'S Instant Irish Oatmeal, Variety Pack o..."
...,...,...,...,...,...
568318,B0013Z0PTW,4,Good Tasting Granola Bars,Most health bars taste awful. Fiber One Grano...,"Fiber One Chewy Bars, Oats and Caramel, 5 - 1...."
568379,B000H28ABW,4,Good and natural,Grab some flavor and save yourself some chemic...,Wick Fowler's Famous Taco Seasoning 1.25 oz. P...
568407,B0039KE8Y2,4,great taste,This apple butter has a great taste but the pr...,"Homestyle Apple Butter, 4.5 oz"
568421,B004BY23I8,4,Co-co-yummy!,Love the coconut flavor of this tea. Two thin...,"Pacific Chai Tea, Coconut Chai Latte, 10-Ounce..."
568440,B000NY4SAG,4,a-ok,We need this for a recipe my wife is intereste...,Castella Ammonia Powder ( 28 g )

In [7]:
# Uses a Huggingface NER pipeline to find matches
def pipeline_entity_ranges(input_text, pipeline, avoid_list=[]):
    # Returns: list of dictionaries ([{type, value, begin, end}])
    entity_ranges = []
    avoid_list = [al.lower() for al in avoid_list]
    ner_results = pipeline(input_text)
    for entry in ner_results:
        if entry['word'].lower() not in avoid_list:
            entity_ranges.append({'type': entry['entity_group'],
                                  'value': entry['word'],
                                  'begin': entry['start'],
                                  'end': entry['end']}
                                )
    return(entity_ranges)

In [8]:
# Uses regex to find additional entity matches

def regex_entity_ranges(input_text, regex_list, avoid_list=[]):
    # regex_list = [[type, expression]],
    #    e.g., ['PHONE', r'[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}']
    
    matches = []
    avoid_list = [al.lower() for al in avoid_list]
    # The list determines order. If any matches overlap, this function keeps the first match found and discards the newer one
    for match_entry in regex_list:
        (etype, exp) = match_entry
        for re_match in re.finditer(exp, input_text):
            overlap = False
            for existing_match in matches:
                if re_match.start() <= existing_match['end'] and existing_match['begin'] <= re_match.end():
                    overlap = True
                    break

            if not overlap and re_match.group().lower() not in avoid_list:
                matches.append({'type': etype,
                                'value': re_match.group(),
                                'begin': re_match.start(), 
                                'end': re_match.end()}
                              )
    return matches

In [9]:
# Combines output from the above two functions
def find_all_entities(text, pipelines=[], regex_patterns=[], avoid_list=[] ):
    intermediate_results = []
    if type(pipelines) != type([]):
        pipelines = [pipelines]
    for pipeline in pipelines:
        intermediate_results += pipeline_entity_ranges(text, pipeline, avoid_list)
        
    intermediate_results += regex_entity_ranges(text, regex_patterns, avoid_list)

    # Deduplicate / de-overlap
    #### TODO ####
    # Right now, this block will drop anything that overlaps previously-found entities.
    # For instance if Model 1 finds "Newcastle" and Model 2 finds "Newcastle upon Tyne", the better match gets dropped
    # We could modify the existing match to least(beginning) - greatest(ending), but what if the entity types are different?
    # In this case we may need to create a new "entity type" of "Unknown" or similar?
    final_results = []
    for ir in intermediate_results:
        add_to_final = True
        for fr in final_results:
            if ir['begin'] <= fr['end'] and fr['begin'] <= ir['end']:
                add_to_final = False
        if add_to_final:
            final_results.append(ir)

    return(final_results)

In [10]:
# Given a list of matches, redacts text
def redact_text(text, found_entity_list=[]):
    text_chunks = []
    last_end_pos = 0
    # The logic below needs the entity list in left-to-right order to work.
    sorted_entity_list = sorted(found_entity_list, key=lambda x: x['begin'])
    
    for entity in sorted_entity_list:
        (etype, ebegin, eend) = (entity['type'], entity['begin'], entity['end'])
        text_chunks.append(text[last_end_pos:ebegin])
        # Standardize type redactions for comparison
        redact_dict = {'PER': 'PERSON'}
        text_chunks.append(f"""[{redact_dict.get(etype) or etype}]""")
        last_end_pos = eend
    text_chunks.append(text[last_end_pos:])
    return ''.join(text_chunks)

In [10]:
# Many product names have people/place names in them. Add the whole product name and two-word chunks to the ignore list.
# Also, these are Amazon reviews, so we'll add "Amazon"
def product_name_to_ignore_list(product_name):
    ignore_list = str(product_name).split(' ')
    for i in range(len(ignore_list) - 1):
        ignore_list.append(' '.join(ignore_list[i:i+2]))
    ignore_list.append('Amazon')
    return ignore_list

In [11]:
regex_list = [['PHONE',r'[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}'],
              ['NUMBER',r'[0-9]{3,}']
             ]

In [13]:
pd.DataFrame(
find_all_entities('My phone number is (315) 555-1212 and I live at 9980 Timberwood Circle.',[dbert_nlp],regex_list,[])
)

     type              value  begin  end
0     LOC  Timberwood Circle     53   70
1   PHONE     (315) 555-1212     19   33
2  NUMBER               9980     48   52

In [14]:
test_1 = 'Robert lives in Fishers, Indiana. His wife Linda works at Olive Garden.'
pd.DataFrame(find_all_entities(test_1, dbert_nlp))

  type         value  begin  end
0  PER        Robert      0    6
1  LOC       Fishers     16   23
2  LOC       Indiana     25   32
3  PER         Linda     43   48
4  LOC  Olive Garden     58   70

In [15]:
test_1_res = find_all_entities(test_1, dbert_nlp)
print(redact_text(test_1, test_1_res))

[PERSON] lives in [LOC], [LOC]. His wife [PERSON] works at [LOC].

In [16]:
# Try it with more nonsense words not in a corpus
test_2 = 'Juspana lives in Polto, Unamia. Her wife Reke works at Norberop.'
pd.DataFrame(find_all_entities(test_2, dbert_nlp))

  type     value  begin  end
0  PER   Juspana      0    7
1  LOC     Polto     17   22
2  LOC    Unamia     24   30
3  PER      Reke     41   45
4  ORG  Norberop     55   63

In [17]:
test_2_res = find_all_entities(test_2, dbert_nlp)
print(redact_text(test_2, test_2_res))

[PERSON] lives in [LOC], [LOC]. Her wife [PERSON] works at [ORG].

In [18]:
# This just combines the find and redact functions
def process_text(text):
    entities = find_all_entities(text, [dbert_nlp, uncased_nlp])
    return redact_text(text, entities)

### TRY THIS FOR YOURSELF. GIVE ME A SENTENCE.

In [22]:
# This one is hard mode. Mixes names that may also be English words. And no capitalization.
sentence = "Who's on first? Exactly!"
print(process_text(sentence))

Who's on first? Exactly!

### Do this for the Google Reviews dataset. Store results in CSV.
#### As we go, we'll print the first few examples of both no redaction.

In [19]:
# BRING IT ALL TOGETHER!
def process_review(text, product_name):
    ignore_list = product_name_to_ignore_list(product_name)
    entities = find_all_entities(text, [dbert_nlp, uncased_nlp], regex_patterns=regex_list, avoid_list=ignore_list)
    redacted = redact_text(text, entities)
    return redacted
    
def process_review_row(row):
    return process_review(row['Text'], row['ItemName'])

In [22]:
# This still doesn't work too well with possessives. Need to look at this more.
process_review('I WAS VISITING MY FRIEND NATE THE OTHER MORNING AND WE HAD MCCANN''S OATMEAL', 'MCCANN''S')

'I WAS VISITING MY FRIEND [PERSON] THE OTHER MORNING AND WE HAD MCCANNS OATMEAL'

In [23]:
# This can take a little while to run on a laptop. It's going through about 25K reviews.
# It would go faster on a GPU with some re-tooling, but this is just a demo.
reviews_4star_df['RedactedReview'] = reviews_4star_df.apply(process_review_row, axis=1)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
C:\Users\BrittonGray\AppData\Local\Temp\ipykernel_14012\479608492.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews_4star_df['RedactedReview'] = reviews_4star_df.apply(process_review_row, axis=1)

In [24]:
reviews_4star_df = reviews_4star_df.drop(columns=['ProductId','Score','Summary'])
reviews_4star_df

,Text,ItemName,RedactedReview
Id,,,
6,I got a wild hair for taffy and ordered this f...,"Salt Water Taffy - Assorted, 5 lbs",I got a wild hair for taffy and ordered this f...
14,good flavor! these came securely packed... the...,"TWIZZLERS Twists, Strawberry Flavored Licorice...",good flavor! these came securely packed... the...
28,I was so glad Amazon carried these batteries. ...,"TWIZZLERS Twists, Strawberry Flavored Licorice...",I was so glad Amazon carried these batteries. ...
33,McCann's Instant Oatmeal is great if you must ...,"McCANN'S Instant Irish Oatmeal, Variety Pack o...",[ORG]'s Instant Oatmeal is great if you must h...
34,This is a good instant oatmeal from the best o...,"McCANN'S Instant Irish Oatmeal, Variety Pack o...",This is a good instant oatmeal from the best o...
...,...,...,...
568318,Most health bars taste awful. Fiber One Grano...,"Fiber One Chewy Bars, Oats and Caramel, 5 - 1....",Most health bars taste awful. Fiber One [ORG]...
568379,Grab some flavor and save yourself some chemic...,Wick Fowler's Famous Taco Seasoning 1.25 oz. P...,Grab some flavor and save yourself some chemic...
568407,This apple butter has a great taste but the pr...,"Homestyle Apple Butter, 4.5 oz",This apple butter has a great taste but the pr...
568421,Love the coconut flavor of this tea. Two thin...,"Pacific Chai Tea, Coconut Chai Latte, 10-Ounce...",Love the coconut flavor of this tea. Two thin...
568440,We need this for a recipe my wife is intereste...,Castella Ammonia Powder ( 28 g ),We need this for a recipe my wife is intereste...

In [25]:
rlist = reviews_4star_df[reviews_4star_df['RedactedReview'].str.contains(r'\[PERSON\]')]['RedactedReview'].tolist()
print('\n\n'.join(rlist[0::20]))

I WAS VISITING MY FRIEND [PERSON] THE OTHER MORNING FOR COFFEE , HE CAME OUT OF [MISC] STORAGE ROOM WITH ( A PACKET OF [PERSON] INSTANT IRISH OATMEAL .) HE SUGGESTED THAT I TRY IT FOR MY OWN USE ,IN MY STASH . SOMETIMES [PERSON] DOSE NOT GIVE YOU A CHANCE TO SAY NO , SO I ENDED UP TRYING THE APPLE AND [LOC] . FOUND IT TO BE VERY TASTEFULL WHEN MADE WITH WATER OR POWDERED MILK . IT GOES GOOD WITH O.J. AND COFFEE AND A SLICE OF TOAST AND YOUR READY TO TAKE ON THE WORLD...OR THE DAY AT LEAST..  [PERSON]...

These [PERSON]'s Signature Beyond Gourmet "Bacon" jelly beans do indeed taste like a very sweet and smokey piece of bacon. This is not flavor that I'm going to snack on, but would make a great gift for the many "bacon fanatics" out there. My wife commented that with a little vinegar flavor added in, they would taste like [MISC] [MISC] Dressing.<br /><br />This flavor is from [PERSON], the creator of the famous "[MISC]" jelly beans, so I was thrilled to be offered this in <a href="http://www.amazon.com/gp/product/B[NUMBER]JBO41E">[PERSON]'s Signature [MISC] Flavor Sampler</a> to review since my family loves jelly beans.<br /><br />I also really like that these jelly beans are made with natural flavors and colors.<br /><br />CFH

Not a writer but this [MISC] is the best in the area [LOC] where I use to buy it at [PERSON]'s. We start buying it through amazon because [PERSON]'s stop stocking [MISC], so I hit the net in search of it. It is very tasty on popcorn better than any other power popcorn salt that's been tried by our family. I highly recommend [MISC] to all.

I bought these jimmies because I couldn't find the needed orange color in any of my local stores.  A pound of jimmies is a lot, but I went through more than I expected, probably half the bag to thoroughly coat a recipe of chocolate truffles.  The taste is, well, jimmy-taste.  My only disappointment/surprise was how short these jimmies are -- about two-thirds of the length of [ORG] and [ORG] brands I have in the cupboard.<br /><br />If you need a special color that only CK makes, don't hesitate to get them.<br /><br />-- [PERSON]

I think Puroast does a pretty good job with low-acid coffee. Low-acid coffee is a very small market and there are very few coffee roasters who are willing to make a low-acid coffee. In [LOC], Puroast and [PERSON] [ORG]'s [MISC] are the only brands I have ever come across in my travels.<br /><br />I gave Puroast four stars because it does not come in whole bean form. I personally prefer fresh-ground coffee and think the pre-ground versions so not stay fresh for as long. I think the flavor, which is pretty good, would be much improved with whole beans. But for those who need a low-acid coffee, and don't mind that it is pre-ground, Puroast is a good choice... especially considering how few choices there are.

I have ordered Bonne Maman Preserves for well over a year from Amazon because the prices could not be beaten anywhere in my area.  The third order back arrived with the jars broken due to poor packing.  Ironically this order was not filled by Amazon but a different vendor.  Nevertheless Amazon promptly refunded my money.  I was a little hesitant about ordering again because of this (broken jars of preserves can be pretty messy)but when I realized that the order was filled by a vendor I had not used before not Amazon, I decided to order again. That order arrived with no problem and since then I have ordered again several times with no issues at all. Each of the glass jelly jars "arrived alive", carefully packed.  Of course the preserves and jelly are the best I have tasted rivaling "homemade" (which we used to do when we were younger and into canning several fruits and vegetables".  In my opinion I like the [MISC] and [MISC] preserves the best so usually I order the six packs of those specifically  j rather than the assortment.  I have to admit however when my granddaughter stays with us she is a huge fan of her "[PERSON]'s"  special strawberry preserves and peanut butter sandwiches. I would recommend that when you order look closely at the vendor who will fulfill the order and go with Amazon.  Generally I look for the "This order ships free with..." and that offer will usually be fulfilled by Amazon.

Ok So I saw a Video of this online and I was like [PERSON] I really want to make this at home. So I bought it and Wow the shipping is fast.  I've bought things from different countries and this shipping is fast considering that it's from [LOC]. Well let me tell you about my experience with this candy.  Making it is fun it takes about 10-15 mins. to make it and you can get the instructions in [MISC] from [...]. The best part was making the fish eggs. The texture of the fish eggs is cool because it is like a skin around the egg and liquid in the center.  The rice smells like Sour apple and the fish eggs were sweet. The taste of the [MISC] gelatin ([MISC]) and the egg gelatin ([MISC] [MISC]) was not too tasty.  It felt weird and not normal in my mouth and wouldn't eat it again.<br />I consider  this to be a fun little gift for a young teen or a kid that likes to make food.

This is a very rich version of [MISC] "custard" (not set, more like our vanilla pudding). It is usually served hot. I prefer [PERSON]'[MISC], which is a powdered mix that you add to milk and then sweeten to taste. I can make it with skim milk and halve the sugar and it makes a great creamy sauce to pour over a fruit crisp. This stuff is good, too, but it's a bit thick and sweet for my personal taste. Still, sometimes I find I crave it (and their rice pudding as well). It reminds me of the custard in many creme brulees, so if you enjoy that level of richness, you should give this a try.

I happily accepted a review bar as I am a fan of [PERSON]'s Own chocolate, usually buying the orange flavored version of this bar <a href="http://www.amazon.[ORG]/gp/product/B[NUMBER]NHSQYU">[PERSON]'s Own [MISC], 3.25-Ounce Bars (Pack of 12)</a>.  (All [MISC] bars are available in both 2.25 oz and 3.25 oz sizes.)<br /><br />With only 54% cocoa, this bar is not particularly dark tasting, for people who are extra-dark chocolate fans.  To my taste, it is somewhat sweet (not bitter) and almost creamy.  For those wanting a darker chocolate, [ORG]'[ORG] does have a 70% cocoa bar: <a href="http://www.amazon.[ORG]/[ORG]/product/B[NUMBER]NHSQRM">[PERSON]'s Own [MISC] (70%) Chocolate [MISC], 3.25-Ounce Bars (Pack of 12)</a>.<br /><br />I prefer this bar (and its various-flavored versions) to the higher cocoa content bars as an everyday treat that I can have a bit of here and there and enjoy a silky chocolate flavor and yet not feel over-caffeinated afterwards.

I am surprised to see so many strong negative reviews for "[ORG]s Own [MISC]". Personally, I find the taste to be delicious; it (the taste) is rich in chocolate flavor, while also avoiding the overly-sweet sugar taste that is common with lower-end chocolate confections. "[PERSON]'s [MISC]" also manages to minimize the bitter taste that is common for dark chocolate, which is a huge plus for me, considering that I am not a big fan of dark chocolate in the first place.<br /><br />In all, highly recommended.

You will really need to love the flavor of ginger to enjoy this tea.  I mixed it according to the package directions and [PERSON] and I shared it.  It was VERY strong on ginger, as if I had cut up a fresh ginger root and grated it into the tea.  I was taken aback at the first sip because of the ginger, however, it began to grow on me.  I did pour a couple of tablespoons of half and half creamer into our cups and that softened the ginger flavor some.  I don't recall even noticing any lemon flavor.<br /><br />I am currently suffering from a terrible cold and my throat had been very sore for the last couple of days.  Now, I don't know if this tea was the reason or not, but after I finished my cup, (and my husband's since he didn't like the strong ginger flavor), I noticed my throat was no longer sore.  And though I still have the cold at this writing, my throat is still not sore.<br /><br />I give it 4 stars because though it is very strong in ginger, that can be diluted down to one's liking.  After I added the cream I began to really enjoy this tea.  I took a moment or two to get used to it, but afterwards it was really good.  I only received one serving (packet) so I don't have any left to experiment with, but next time I think I would at least double the amount of water from [NUMBER] ml to [NUMBER].

I have been a connoisseur of quality green, oolong for many moons, and I also enjoy a good cup of morning [PERSON]. I had tried loose [MISC]-erh previously and was bitten by the smooth coffee like mouth feel of the variety. This is not green tea taste be prepared, but is very earthy and rich especially during the first and second flushes. These nuggets of goodness have replaced my boring coffee routine. I prefer it strong and thick usually dropping two Tuo Cha nugs in my tea pot. I'm here to report the following; calm alertness, healthy as green and if you believe might help drop a few points on your disappointing cholesterol numbers  before your next visit.<br /><br />It's true......strong earthy aroma is apparent primarily during the first flush, but is very part of the brew process, brew is clear not cloudy and taste is never sharp or tannic. Be warned I've tried the flavored varieties, and filler is not my cup of tea. If you like it sweet add a little honey and say goodbye to the beans!

[PERSON]'s Crunchy Nut is a tasty yet unremarkable breakfast cereal.  I've given it a 4 star rating because I enjoyed it.  Yet at the same time, I probably wouldn't go out of my way to buy it again.<br /><br />One of the main ingredients is peanuts, yet the nut taste is not pronounced.  In fact, I wouldn't have known that it even contains peanuts if I didn't already know.  The flavor reminds me of a cross of regular [MISC] and [MISC].<br /><br />Sugary sweetness is the dominant theme here.  I like sweet, so I'm not complaining too much.  But I suppose they could throttle back on the sweetness a bit.<br /><br />A 3/4 serving provides about 25% of many of the major vitamins, so there is certainly some nutritional benefit to the cereal. It also provides about 8% of your recommended daily allowance of fiber.<br /><br />The ingredients appear to be decent for the most part, although I have no idea what Pyridoxine Hydrochloride is.  The first ingredient is yellow corn meal followed by sugar, corn bran, peanuts, honey, molasses, salt and whole oat flour.  Again, generally not bad at all.  As noted, I'd prefer that they cut back on the sugar, but then I suppose that they probably wouldn't sell as much of the stuff.<br /><br />So I liked it.  I probably won't buy it again, but if someone served it to me in the future, I'd be perfectly happy.  3.5 stars rounded up to 4.

I've heard people for years rave about [PERSON], so how could I resist tasting what all the fuss was about? First made in [LOC], [LOC], in [NUMBER] (now made in [LOC]), the package states that 70% of these cookies are sold "in the shadow of the [MISC]". Eighteen cookies in the carton, 2 cookies per serving at [NUMBER] calories, 5g of fat; unfortunately there's high fructose corn syrup, so I won't buy more.<br /><br />The cookie itself? A B+ in my book. There's a good sweet dark chocolate shell around a fluff of marshmallow atop a cookie. The chocolate and marshmallow are very good together. The cookie has a good flavor but is overpowered by the other two, and it crumbles too much -- I always wind up sprinkled with crumbs; at the end there's a slightly salt finish. Very nice. I can see why people like these, but I'd probably take an [MISC] first.

They are good but need more cheese and wish they were krinkle cut. I much prefer the salt & pepper just for the krinkle cut - they have a better texture. All around this brand is much better than [MISC]-[MISC] and a good price on Amazon when you get free shipping. These are similar to [PERSON]'[MISC] or [PERSON]'s chips in that they are very crispy.<br /><br />On a side note, these are the hardest bags to open by hand. I have to use a knife or scissors everytime.

thrilled to have this assortment as i got the chance to choose another decaf coffee- have already sampled [MISC] [ORG] and [PERSON]- now have more choices-- many thanks to keurig, green mountain and of course amazon

Like many others, the price point of this coffee got my attention but what's the point of cheaper coffee that's all but undrinkable... [LOC], anyone?<br /><br />So before ordering on price alone I wanted to see other reviewers contrast and compare this blend to other k-cups such as [PERSON]'s [MISC], [ORG]'s [MISC] or [ORG] [MISC]. After all, given the wide disparity of opinion about which k-[MISC] blend is bold, strong or rich in flavor, at least finding common ground with others who enjoy the aforementioned brands you can estimate the appeal of the flavor to your own palate.<br /><br />At the time I placed my order I didn't find any clear indicators from other reviewers along these lines, hence for what it's worth, as one who enjoys the previously mentioned k-cups, I can say that overall San Francisco [MISC] measures up pretty darn well to the more expensive brands.<br /><br />Now if cost were not a factor I'm not certain this would be my first choice as this blend has a somewhat smoky after taste and I prefer a more fruity or sweet flavor. But hey, this is [MISC] and as such the taste seems well suited.<br />Nevertheless, no regrets...it's a nice bold brew (with an appealing price) that I look forward each morning.

"Bounty" bars consist of a soft, almost molten center of sweet coconut coated in an outer layer of milk chocolate. You can easily buy them "over the counter" here in [LOC]. But if that's not the case where you are, and you don't mind a diet rich in junk food, then yes, this is a candy bar worth going to the trouble of ordering over the internet.<br /><br />Note that here on Amazon you can purchase bounty bars in boxes with varying numbers of bars inside, so it is worth your while to crunch the numbers and think about what package offers the best value for you. At the same time, it may not be entirely in the best interests of your health to have _too_ many of these things lying around at home all at once!<br /><br />[PERSON].

When my boyfriend found out he was to be [PERSON], he thought he had to give up his favorite dishes, especially those with cream soups.  I have found this cream of celery soup does the job.

[PERSON] eats these and says they are good snacks for the morning. Not too over done on the apple flavor

[PERSON]'s licorice was really good.  It's hard to find organic treats to give my kids that they like as well as the [MISC], corn syrupy garbage found in the candy isle of the grocery store.  [PERSON]'s is a good option.

I love potato chips, it is simple, tasty, crunchy; a mass produced cracker doesn't stand a chance, not to mention a healthy cracker. Embraced healthy food lifestyle for many years now, and had fare share of disappointment when it came to healthy snacking. After many years I ended up with a handful of healthy snacks that not only are healthy, but very tasty. [MISC]'s  [MISC] made the cut the very moment I tried one. I can easily put down a chip for these.<br /><br />TASTE = very nutty-rice-sesame hearty in flavor with a texture sort of like a glazed [MISC] cracker. Delicious indeed<br /><br />When it comes to healthy,its no brainier!<br />Ingredients<br />a. [PERSON] rice = vitamin B1, vitamin B3, and iron<br />b. Quinoa  = dietary fiber, phosphorus, magnesium, iron, calcium, and thus is useful for vegans and those who are lactose intolerant<br />c. Flax seed  = Omega3<br />d. Sesame  = Omega6,antioxidants(sesamin, sesamolin, and sesamol, protein<br />Rest are organic fillers and hebs.<br />  @VS@<br />!!Mass produced crackers have crap like:<br />CULTURED MILK, SALT, PARTIALLY HYDROGENATED COTTONSEED OIL, SALT, AUTOLYZED YEAST EXTRACT, MONOSODIUM GLUTAMATECALCIUM PHOSPHATE, ANNATTO EXTRACT (VEGETABLE COLOR), SODIUM CASEINATE, LACTIC ACID, ACETIC ACID, WHEY (list goes on)<br /><br />Conclusion, if you are a guy looking for a hearty, tasty, flavorful healthy alternative to chips this will fill in that void...<br />Why 4 rating and not 5? Its expensive, and doesn't replicate a fresh home made variations.

My wife and I purchased [PERSON]'s [MISC], [MISC], [MISC] for over two years and used Amazon's subscription to automatic shipping for the best economy.  It was disappointing to learn a few weeks ago that this particular coffee would no longer be available on the subscription program.  We looked over the list of coffees that would be available and selected [MISC] because the label and description included "[MISC]."  We are very satisfied with the new coffee.  It has the strong, rich flavor and aroma we like.  It is difficult to distinguish this Jet Fuel coffee from our old favorite [MISC].  All of the subscription coffees are in boxes of 50 [MISC]-[MISC] which is a little more economical than the former 24 [MISC]-[MISC] boxes.  This savings plus the discount for subscribing to automatic free shipping results in the lowest cost we have found for these [MISC]-Cups.

I purchased this product as well as the Allergaroo spyglass noodles for my grandson who has [PERSON]'s syndrome and is on the [MISC] (gluten free and cassein free)diet.  It's hard to find good food that he can have so I was delighted to find these.  The best part is that he loves them.  He does need two packages for a meal because they're rather small.  By purchasing online in bulk the price is much more reasonable than buying individual packages at the grocery store. It's difficult to give a child a tasty meal when on this diet without doing a lot of home cooking and health food store shopping, but the [MISC] are a nice break from all that; sort of "fast food" for the [MISC] diet.

These are pretty darn good cookies!  I prefer <a href="http://www.amazon.[ORG]/gp/product/B[NUMBER]IAUQ">[PERSON]'s Cinnamon [MISC], 5.5-[MISC] (Pack of 8)</a> but these are a close second.<br /><br />The cookies are crunchy, not chewy.  They do have a lot of sugar on the top but it is only noticeable if you have several at a time.  Seemed sweeter  to me than the cinnamon thins.<br /><br />Not crumbly or cakey.  No funky taste.<br /><br />Only 8 in the package, not very many at all.  Putting that in a positive light, you can consider it built-in portion control.  Handy if you're like me and sometimes happen to snack without actually paying attention to how much you are eating.

2 pounds is a lot of tea. I split the package with my daughter.  I make my loose tea in my [MISC]!!!  I like strong tea, and this tea works for me.<br />I'm still experimenting on tea's, so I'm no professional.  I like the taste.  I use light milk and sugar. That's the way my Irish grandmother, [PERSON], taught me to drink it.

I almost didn't try this because I bought the Walden Farms chocolate sauce and marshmallow sauce several years ago and they were awful.  But thanks to Amazon reviews, I decided enough people liked the salad dressings that I should give them a chance.<br /><br />I found this at my local [PERSON] [ORG] ([PERSON] family) for a few pennies over $5.  The [ORG] stores in [LOC] have a little diet food section, and that's where I found it.  I bought the [ORG] [MISC], and I must say it's pretty good.  I had a full bowl of salad with plenty of dressing (I like lots!) for just 20 calories.  Very cool!<br /><br />I wonder how this would taste on [MISC] (yam) noodles?  I think I'll try that tomorrow.


In [26]:
reviews_4star_df.to_csv('datasets/outputs/food_reviews_huggingface.csv')